### ISSUE TITLE
Fails to install on first attempt with python3.10

### ISSUE THREAD

**Issue by LinuxIsCool** [balancer/balpy#36]
I cloned, and then poetry install fails.

![image](https://user-images.githubusercontent.com/31582215/202839981-50825c0a-feff-4137-8344-ab251952a512.png)

balpy Version 0.0.0a69
Python version 3.10.6

**Comment by gerrrg** [comment]
multicaller is on version 0.0.0a16, so I imagine this was a temporary issue
